version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: randompassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: johndoe
      MYSQL_PASSWORD: randompassword
    volumes:
      - ./data:/var/lib/mysql
